apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: billyang3416/spring-tls-app:latest
          env:
            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-tls-secret
                  key: keystore-password
            - name: KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-tls-secret
                  key: key-password
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/tls-certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: my-tls-secret
